---

- lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: '^\#?PasswordAuthentication ', line: 'PasswordAuthentication no' }
    - { regexp: '^\#?PermitRootLogin ', line: 'PermitRootLogin {{ sshd_permit_root_login }}' }
    - { regexp: '^\#?UseDNS ', line: 'UseDNS {{ sshd_use_dns }}' }
  notify:
    - restart ssh

- lineinfile:
    path: /etc/default/ssh
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: '^SSHD_OPTS=', line: 'SSHD_OPTS="-u0"' }
  notify:
    - restart ssh
