---

- name: "Authprogs Configuration"
  copy: 
    src: "{{ authprogs_site_files_relative_path }}site_files/{{inventory_hostname}}/root/.ssh/authprogs.yaml"
    dest: "/root/.ssh/"

- name: "Authprogs Keys"
  copy:
    src: "{{ authprogs_site_files_relative_path }}site_files/{{inventory_hostname}}/root/.ssh/authorized_keys"
    dest: "/root/.ssh/"
