---

- name: "Authprogs Configuration"
  copy: src="site_files/{{inventory_hostname}}/root/.ssh/authprogs.yaml"  dest="/root/.ssh/"

- name: "Authprogs Keys"
  copy: src="site_files/{{inventory_hostname}}/root/.ssh/authorized_keys" dest="/root/.ssh/"
